{% set name = "evv4esm" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: caf87615fbbbcf2aaf004a8fd8bc7cd3bc028f0b60427107d25ee4a871dca9bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - evv = evv4esm.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - six
    - numpy
    - scipy
    - pandas
    - livvkit >=3.0.1
    - netcdf4
    - matplotlib-base
    - pybtex
    - statsmodels

test:
  imports:
    - evv4esm
  commands:
    - evv --version

about:
  home: https://github.com/LIVVkit/evv4esm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended verification and validation of Earth system models

  # The remaining entries in this section are optional, but recommended.
  description: |
    EVV is a python-based toolkit for extended verification and validation of
    Earth system models (ESMs). Currently, it provides a number tests to
    determine if modifications to an ESM is climate changing.
  doc_url: https://github.com/LIVVkit/evv4esm
  dev_url: https://github.com/LIVVkit/evv4esm

extra:
  recipe-maintainers:
    - jhkennedy
    - mkstratos
