{% set name = "evv4esm" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b70d1aa4f58a7eaa3a10c6a90b691e418b15bb3a19ee5a7851236f7d1cf49a86

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - evv = evv4esm.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - numpy
    - scipy
    - pandas
    - livvkit >=3.0.1
    - netcdf4
    - matplotlib-base
    - pybtex
    - statsmodels ==0.14.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - evv4esm
  commands:
    - evv --version

about:
  home: https://github.com/LIVVkit/evv4esm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended verification and validation of Earth system models

  # The remaining entries in this section are optional, but recommended.
  description: |
    EVV is a python-based toolkit for extended verification and validation of
    Earth system models (ESMs). Currently, it provides a number tests to
    determine if modifications to an ESM is climate changing.
  doc_url: https://github.com/LIVVkit/evv4esm
  dev_url: https://github.com/LIVVkit/evv4esm

extra:
  recipe-maintainers:
    - jhkennedy
    - mkstratos
